sudo: required
dist: trusty
os: linux
language: minimal
cache:
  apt: true
  ccache: true
  directories:
  - depends/built
  - depends/sdk-sources
  - "$HOME/.ccache"
env:
  global:
  - MAKEJOBS=-j5
  - CCACHE_SIZE=400M
  - CCACHE_TEMPDIR=/tmp/.ccache-temp
  - CCACHE_COMPRESS=1
  - SDK_URL=https://bitcoincore.org/depends-sources/sdks/
  - LASTTAG=$(git describe --tags)
  - TAG="$LASTTAG"
  matrix:
  - HOST=x86_64-apple-darwin14 PACKAGES="cmake imagemagick libcap-dev librsvg2-bin
    libz-dev libbz2-dev libtiff-tools python-dev zip unzip libc6-dev libc6-dev-amd64"
    BITCOIN_CONFIG="--enable-gui --enable-reduce-exports --disable-tests --disable-bench"
    OSX_SDK=10.11 GOAL="deploy"
before_install:
- travis_retry sudo apt-get install python-dev
- export PATH=$(echo $PATH | tr ':' "\n" | sed '/\/opt\/python/d' | tr "\n" ":" |  sed
  "s|::|:|g")
install:
- if [ -n "$DPKG_ADD_ARCH" ]; then sudo dpkg --add-architecture "$DPKG_ADD_ARCH" ;
  fi
- if [ -n "$PACKAGES" ]; then travis_retry sudo apt-get update; fi
- if [ -n "$PACKAGES" ]; then travis_retry sudo apt-get install --no-install-recommends
  --no-upgrade -qq $PACKAGES; fi
before_script:
- unset CC; unset CXX
- mkdir -p depends/SDKs depends/sdk-sources
- if [ -n "$OSX_SDK" -a ! -f depends/sdk-sources/MacOSX${OSX_SDK}.sdk.tar.gz ]; then
  curl --location --fail $SDK_URL/MacOSX${OSX_SDK}.sdk.tar.gz -o depends/sdk-sources/MacOSX${OSX_SDK}.sdk.tar.gz;
  fi
- if [ -n "$OSX_SDK" -a -f depends/sdk-sources/MacOSX${OSX_SDK}.sdk.tar.gz ]; then
  tar -C depends/SDKs -xf depends/sdk-sources/MacOSX${OSX_SDK}.sdk.tar.gz; fi
script:
- cd $TRAVIS_BUILD_DIR/depends
- make $MAKEJOBS HOST=$HOST $DEP_OPTS
- cd $TRAVIS_BUILD_DIR
- "./autogen.sh"
- CONFIG_SITE=$TRAVIS_BUILD_DIR/depends/$HOST/share/config.site ./configure $BITCOIN_CONFIG_ALL
  $BITCOIN_CONFIG --prefix=$TRAVIS_BUILD_DIR/../graphcoin-$HOST-$TAG
- make $MAKEJOBS $GOAL || ( echo "Build failure. Verbose build follows." && make $GOAL
  V=1 ; false )
before_deploy:
- if [ "$HOST" == "x86_64-apple-darwin14" ]; then mv Graphcoin-Core.dmg Graphcoin-Core-$TAG-macosx-generic.dmg;
  FILE=Graphcoin-Core-$TAG-macosx-generic.dmg; fi
- if [ "$HOST" == "x86_64-w64-mingw32" ]; then cd $TRAVIS_BUILD_DIR/../; zip -r graphcoin-$TAG-win-x64.zip
  graphcoin-$HOST-$TAG; mv graphcoin-$TAG-win-x64.zip $TRAVIS_BUILD_DIR/; cd $TRAVIS_BUILD_DIR;
  FILE="graphcoin-$TAG-win-x64.zip"; fi
- if [ "$HOST" == "i686-w64-mingw32" ]; then cd $TRAVIS_BUILD_DIR/../; zip -r graphcoin-$TAG-win-x32.zip
  graphcoin-$HOST-$TAG; mv graphcoin-$TAG-win-x32.zip $TRAVIS_BUILD_DIR/; cd $TRAVIS_BUILD_DIR;
  FILE="graphcoin-$TAG-win-x32.zip"; fi
- if [ "$HOST" == "i686-pc-linux-gnu" ]; then cd $TRAVIS_BUILD_DIR/../; zip -r graphcoin-$TAG-$HOST.zip
  graphcoin-$HOST-$TAG; mv graphcoin-$TAG-$HOST.zip $TRAVIS_BUILD_DIR/; cd $TRAVIS_BUILD_DIR;
  FILE="graphcoin-$TAG-$HOST.zip"; fi
- if [ "$HOST" == "x86_64-pc-linux-gnu" ]; then cd $TRAVIS_BUILD_DIR/../; zip -r graphcoin-$TAG-$HOST.zip
  graphcoin-$HOST-$TAG; mv graphcoin-$TAG-$HOST.zip $TRAVIS_BUILD_DIR/; cd $TRAVIS_BUILD_DIR;
  FILE="graphcoin-$TAG-$HOST.zip"; fi
- if [ "$HOST" == "arm-linux-gnueabihf" ]; then cd $TRAVIS_BUILD_DIR/../; zip -r graphcoin-$TAG-$HOST.zip
  graphcoin-$HOST-$TAG; mv graphcoin-$TAG-$HOST.zip $TRAVIS_BUILD_DIR/; cd $TRAVIS_BUILD_DIR;
  FILE="graphcoin-$TAG-$HOST.zip"; fi
deploy:
  provider: releases
  api_key:
    secure: qyWI/JOXalKsfedRATnO3wk2+ARlEYxTuB0JsiWE3le6lS20AEAwipgnuQSGjAK0Wsrhom3yem/DTmo7QgkIbHtUcnfPM7w0EfTv6ZHqKVQ7lw/JliCi7JC2Hr+qRY9oEcx+DeuLZvX5BsRIEWM5O8oY4v+7VjbvaxqD3Q7f/CFcFfO445tGhARzv7iMQ+b5Dstb5IyyJXPWvBbCsZJzwfC+r8dfjypL5UiyjaW5hrzgxrV7QkSoQXFRc1/WMuMcv2k+wh7842hoWhdsUb14w+SbKk6hpWf6m2xsPhKq+EG6DRjf8LaAtvO1fbj11k2riPJJ5ZWlxHlRmcLKRj8HtwzYwg4eOU1XmujClU0zJ9hJ9oR/g47nZeHHYoEjmMhaDKOG8uv6S1ckbHevT8r/ywbG0bVqE/nh7lJa79K8Vo+IJi3P9gzi/dkcu8VnXt3JhV7aZD4ZCT2Lsr/PghukURhpz+bIaASnNTaJdxgunLsqlz9OluPIxjOAoHr7AFER+9KYxcX0W8rrV61r7+oZfQxcHtsSMU4tqeyNDpWWaL1LPegBpY7Pz9L06XVE1Kde9XP8D8D2IRttJKOUpV+0dAJrvq6g0ZwP1ThY+XsG/wV1Y3GS7FXNDPJMxjfU+xLXpW7jdlFGw1jsNdy08UlNoKyXHN3i1ToNshXMv7loaVg=
  file: "$FILE"
  on:
    repo: ScaMar/source-1
    branch: master
    tags: true
  skip_cleanup: true
